language: node_js
node_js:
  - "0.12"

services:
  - redis-server

before_script:
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - apt-get update
  - apt-get install rethinkdb
  - echo "cache-size=3072" >> /etc/rethinkdb/instances.d/default.conf
  - service rethinkdb start